version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - .docker/nginx/conf.d:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: files
    restart: always

volumes:
  postgres_data: